name: Verify Pull request is correct

on:
  pull_request:
    branches:
      - develop

env:
  GITHUB_USERNAME: "fknives"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Java Unit Tests
        run: ./gradlew processor:test
      - uses: actions/upload-artifact@v2
        with:
          name: Java Unit Test Results
          path: processor/build/reports/tests/test/index.html
          retention-days: 1